[workspace]
members = [
    "v0_old",
    "v1_cus_regex",
    "v2_cover",
    "v3_mem",
    "v4_stack",
    "v5_literal",
    "x1_cover_bs_reg",
    "x2_numbers",
]

[profile.release]
lto = "fat"
codegen-units = 1
